dataset_params:
  # train_im_sets: ['D:\VOC\VOC2007_trainval\VOCdevkit\VOC2007', 'D:\VOC\VOC2012_train_val\VOC2012_train_val']
  test_im_sets: ['D:\VOC\VOCUE_2objs']
  im_size : 300
  transform_name : 'ssd'
  num_classes : 31
  # resize_longer_edge
  # roi_crop_test_transform
  # letterbox
  # ssd
  # no_resize_transform
  # fixed_padding_roi_crop_X

train_params:
  dataset: 'voc-vid'
  infer_conf_threshold : 0.5
